# Generated by Django 2.1.2 on 2018-10-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.TextField(blank=True, max_length=500)),
                ('country', models.TextField(blank=True, max_length=500)),
                ('city', models.TextField(blank=True, max_length=500)),
                ('delivery_address', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
