# Generated by Django 2.1.2 on 2018-10-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181015_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Cart', verbose_name='Cart'),
        ),
    ]
